"""doc_freshness.py — three structural asserts against documentation rot.

Rot in this repo has never been a vigilance failure, so the mitigation is not vigilance.
Each assert below closes a class that has ALREADY bitten, and each is checked mechanically:

  A1  NO `FILE:NNN` pointers in living docs — cite a grep-able string instead.
      Class G. Bitten 6x in one audit (`STRATEGY.md:804` -> :906 etc.), and once
      inside the very file that rails against it (instance 13, ledger in STRATEGY.md).

  A2  The look counter's VALUE lives in EXACTLY ONE file. Every other doc points.
      Bitten immediately: `docs/STATUS.md` carried 535 while the owner said 557.

  A3  FAST-MOVING FACTS (partition counts, hole-day counts, migration state) live only
      in `docs/STATUS.md`. Bitten hours after being written: `CLAUDE.md` asserted
      "dry-run only, 0 deletes" while the real run was deleting in the background.

## Why this cannot become a class-I verifier

A checker that fires on correct work destroys it. Three escapes exist, all EXPLICIT and
all PRINTED on every run so nothing hides behind them:

  * `[HISTORICAL]` on the line — the pointer/number is quoted AS a record of the past
    (the instance-13 ledger row must be able to quote the stale pointer it documents).
  * `~~strikethrough~~` on the line — a superseded value kept for the audit trail.
  * A1/A3 only: a `20YY-MM-DD` date stamp on the line makes a number a dated
    MEASUREMENT rather than a current-state claim. A3 only; A1 pointers rot regardless
    of when they were written.
  * ARCHIVAL files (below) are append-only records of the past, not living guidance.

Every exemption is counted and printed. An exemption that stops being true shows up as a
number that stops matching, not as silence.

Research-only, read-only: opens files, writes nothing.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Append-only records of the past. A pointer inside a 2026-07-13 run-log was correct on
# 2026-07-13; freezing it is the point. Living guidance is everything NOT listed here.
ARCHIVAL = {
    "AUDIT_LOG.md": "dated incident log, append-only",
    "THIRD-PARTY.md": "third-party license/provenance record",
    "RESEARCH-partB-runlog.md": "dated run-log",
    "RESEARCH-orderflow-runlog.md": "dated run-log",
    "RESEARCH-vision-runlog.md": "dated run-log",
    "RESEARCH-tharp-runlog.md": "dated run-log",
    "RESEARCH-ic-runlog.md": "dated run-log",
    "RESEARCH-dsr-convention.md": "dated decision record",
}
ARCHIVAL_DIRS = ("reports/incident-",)          # frozen incident bundles

# GENERATED artifacts: machine-written from the owners on every `make gate`, never hand
# edited, so a second copy of a fast-moving value there cannot go stale independently.
# Exempt from A2/A3 only — a generated file has NO excuse for emitting a file:line pointer,
# so A1 still applies to it. The exemption is safe BECAUSE the gate regenerates the file;
# if that ever stops being true, this line is the thing to delete.
GENERATED = {"docs/HANDOFF.md": "regenerated by `make handoff`, last step of `make gate`"}

COUNTER_OWNER = "docs/EDA-microstructure-001.md"
STATE_OWNER = "docs/STATUS.md"

SKIP_DIRS = {".git", "node_modules", ".venv", "venv", "__pycache__", ".tmp", "data"}
# The fixtures ARE deliberate violations; scanning them from the repo root would make the
# gate fail on its own test corpus. tests/test_doc_freshness.py points --root at them.
SKIP_PATH_PARTS = ("tests/fixtures/doc_freshness",)

# A1 — path-with-extension followed by a line number.
POINTER = re.compile(
    r"\b[A-Za-z0-9_][A-Za-z0-9_/.-]*\.(?:py|md|js|cjs|mjs|json|yml|yaml|toml|txt|sh|ini|cfg)"
    r"\s*:\s*\d+(?:\s*[-–]\s*\d+)?\b")

# A2 — a look-counter VALUE (a pair of numbers), in any of its published shapes.
COUNTER_VALUE = re.compile(
    r"(?:look\s*counter[^|\n]{0,80}?\b\d{2,4}\b[^|\n]{0,40}?\b\d{1,4}\b)"
    r"|(?:\b\d{2,4}\s*(?:diagnostic|diagnostik)\b[^|\n]{0,40}?\b\d{1,4}\b)"
    r"|(?:running\s*total\D{0,20}\d{2,4}\D{1,20}\d{1,4})"
    r"|(?:\b\d{2,4}\s*/\s*81\b)", re.IGNORECASE)

# A3 — fast-moving facts.
# PRECISION NOTE (class I). The first version matched any 4-digit comma number within 60
# chars of "partition" and produced false positives on print counts ("28,428 prints ...
# hive partition"), timings ("11.9 s/partition") and commit counts ("2,084 commits").
# A verifier that cries wolf destroys correct work, so the count must be ADJACENT to the
# word and the line must not be about a different unit.
_NOT_A_PARTITION_COUNT = re.compile(
    r"s/partition|per partition|\bcommits?\b|\bprints?\b|\bbars?\b|\bMB\b|\brows?\b",
    re.IGNORECASE)

STATE_PATTERNS = [
    ("partition count",
     re.compile(r"\b\d{1,2},\d{3}\b[^\n]{0,14}?(?:day-)?partitions?\b"
                r"|(?:\bpartitions?\b[^\n]{0,14}?\b\d{1,2},\d{3}\b)", re.IGNORECASE)),
    ("hole-day count",
     re.compile(r"\b(?:29[0-9]|30[0-9])[-\s]day\s+(?:archive\s+)?hole\b", re.IGNORECASE)),
    ("migration state",
     re.compile(r"MID-FLIGHT|dry-run only|0 deletes|local copies intact"
                r"|deleted so far|migration is (?:running|under way)",
                re.IGNORECASE)),
]

DATE_STAMP = re.compile(r"\b20\d\d-\d\d-\d\d\b")
HISTORICAL = "[HISTORICAL]"


def is_archival(rel: str) -> bool:
    return rel in ARCHIVAL or any(rel.startswith(d) for d in ARCHIVAL_DIRS)


def exempt(line: str, allow_date: bool) -> str | None:
    """Return the exemption reason, or None when the line must be judged."""
    if HISTORICAL in line:
        return "[HISTORICAL] marker"
    if "~~" in line:
        return "struck through"
    if allow_date and DATE_STAMP.search(line):
        return "dated measurement"
    return None


def md_files(root: Path):
    root_abs = root.resolve()
    for p in sorted(root.rglob("*.md")):
        if any(part in SKIP_DIRS for part in p.parts):
            continue
        rel = str(p.resolve().relative_to(root_abs))
        if any(sk in rel for sk in SKIP_PATH_PARTS):
            continue
        yield p


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", type=Path, default=REPO)
    ap.add_argument("--counter-owner", default=COUNTER_OWNER)
    ap.add_argument("--state-owner", default=STATE_OWNER)
    ap.add_argument("--quiet-exempt", action="store_true",
                    help="count exemptions without listing them")
    a = ap.parse_args()

    v1: list[str] = []
    v2: list[str] = []
    v3: list[str] = []
    ex = {"[HISTORICAL] marker": 0, "struck through": 0, "dated measurement": 0,
          "archival file": 0, "generated artifact": 0}
    ex_lines: list[str] = []
    counter_files: set[str] = set()
    n_files = 0

    for p in md_files(a.root):
        rel = str(p.relative_to(a.root))
        n_files += 1
        archival = is_archival(rel)
        for i, line in enumerate(p.read_text(errors="replace").splitlines(), 1):
            # ---- A1: FILE:NNN pointers ----
            for m in POINTER.finditer(line):
                if archival:
                    ex["archival file"] += 1
                    continue
                why = exempt(line, allow_date=False)
                if why:
                    ex[why] += 1
                    ex_lines.append(f"    A1 {rel}:{i} exempt ({why}): {m.group(0)}")
                    continue
                v1.append(f"    {rel}:{i}  ->  {m.group(0)}")
            # ---- A2: look-counter values ----
            if COUNTER_VALUE.search(line):
                if archival or rel in GENERATED:
                    ex["generated artifact" if rel in GENERATED else "archival file"] += 1
                elif exempt(line, allow_date=False):
                    why = exempt(line, allow_date=False)
                    ex[why] += 1
                    ex_lines.append(f"    A2 {rel}:{i} exempt ({why})")
                else:
                    counter_files.add(rel)
                    if rel != a.counter_owner:
                        v2.append(f"    {rel}:{i}  ->  {line.strip()[:96]}")
            # ---- A3: fast-moving facts ----
            if rel != a.state_owner and not archival and rel not in GENERATED:
                for label, pat in STATE_PATTERNS:
                    m = pat.search(line)
                    if not m:
                        continue
                    if label == "partition count" and _NOT_A_PARTITION_COUNT.search(line):
                        continue          # a different unit shares the sentence
                    why = exempt(line, allow_date=True)
                    if why:
                        ex[why] += 1
                        ex_lines.append(f"    A3 {rel}:{i} exempt ({why}): {label}")
                    else:
                        v3.append(f"    {rel}:{i}  [{label}]  {line.strip()[:88]}")

    # ---- report: every conclusion printed BESIDE the evidence that produced it ----
    print(f"doc-freshness — {n_files} markdown files under {a.root}")
    print(f"  archival files (append-only records, exempt by design): {len(ARCHIVAL)}"
          f" + dirs {ARCHIVAL_DIRS}")
    print(f"  generated artifacts (A2/A3 exempt, A1 still applies): {sorted(GENERATED)}")
    print(f"  counter owner: {a.counter_owner}   state owner: {a.state_owner}\n")

    print(f"  A1  FILE:NNN pointers in living docs      : {len(v1)} violation(s)")
    for line in v1[:40]:
        print(line)
    if len(v1) > 40:
        print(f"    … and {len(v1) - 40} more")

    print(f"  A2  look-counter values outside the owner : {len(v2)} violation(s)")
    print(f"      files carrying a value: {sorted(counter_files) or ['none']}")
    for line in v2[:20]:
        print(line)

    print(f"  A3  fast-moving facts outside the owner   : {len(v3)} violation(s)")
    for line in v3[:30]:
        print(line)
    if len(v3) > 30:
        print(f"    … and {len(v3) - 30} more")

    print(f"\n  exemptions taken: " + " · ".join(f"{k} {v}" for k, v in ex.items()))
    if ex_lines and not a.quiet_exempt:
        for line in ex_lines[:25]:
            print(line)
        if len(ex_lines) > 25:
            print(f"    … and {len(ex_lines) - 25} more exemptions")

    total = len(v1) + len(v2) + len(v3)
    print(f"\n  >>> {'PASS — no documentation rot detected' if total == 0 else f'FAIL — {total} violation(s); fix the doc, do not widen the checker'}")
    return 0 if total == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
